//! `codeatlas serve`: the embedded dashboard over loopback (ticket 09), and
//! — only when asked for — questions about the map (ticket 34).
//!
//! The server is a hand-rolled HTTP/1.1 responder on `std::net::TcpListener`
//! rather than a server crate: four GET routes — one of them flag-gated —
//! and one optional POST, all
//! declared in [`REGISTRY`], the table `handle` dispatches through, with
//! HEAD answered wherever GET is, derived from that same table — plus
//! the embedded-asset fallback, and zero TLS/streaming/routing machinery, so
//! even the smallest server dependency (tiny_http and its transitive tree)
//! would be more code than this file.
//! Under ADR-0006 the serve path must survive a security audit by reading it
//! — a screenful of std with one hardcoded loopback bind is the strongest
//! form of that argument.
//!
//! # The shapes, and each difference is a flag
//!
//! Without `--ask` this process reaches for four things and no others: one
//! listening socket on 127.0.0.1, asset bytes from process memory, the map
//! and overlay from local disk, and one sentence it composes about its own
//! configuration (the capability route below, which is not read from
//! anywhere — it is `routes.ask.is_some()`). Nothing off this host, ever,
//! which is what the netns egress test puts a real subject under.
//!
//! With `--ask` the binary also holds an enrichment provider, and
//! `POST /api/ask` reaches a model through it (ADR-0009). That is opt-in,
//! resolved before the socket is bound so a build or a machine that cannot
//! answer questions says so at startup rather than on the first question.
//!
//! With `--open-code` the binary serves a mapped file's source at
//! `GET /api/source` (ADR-0013). Not an egress path — nothing new leaves
//! the host, and no model receives anything it did not before — but a real
//! widening of what a loopback caller can be told, which is why it is a
//! flag and not a default: a loopback port is readable by any local user,
//! file permissions are not. Without the flag the route does not exist,
//! exactly as the ask route does not.
//!
//! Which of the shapes is running is what `GET /api/capabilities` states,
//! for the dashboard (ticket 27): the same embedded bytes are served either
//! way, so the page has to be told at runtime rather than at build time. It
//! is not in the map, because whether one process was started with a flag is
//! not a property of a map — and the map's schema is a published contract
//! other producers emit against (ADR-0003).

use std::borrow::Cow;
use std::io::{BufRead, BufReader, Read, Write};
use std::net::{Ipv4Addr, Shutdown, TcpListener, TcpStream};
use std::path::{Path, PathBuf};
use std::thread;
use std::time::{Duration, Instant};

use anyhow::{Context, Result, bail};

use crate::enrich::{self, EnrichmentProvider, ProviderChoice, SharedProvider, ask};
use crate::map::{KnowledgeGraph, NodeKind};
use crate::scan::OUTPUT_DIR;

// Generated by build.rs: `ASSETS`, the dashboard production build keyed by
// URL path with precomputed MIME types.
include!(concat!(env!("OUT_DIR"), "/embedded_assets.rs"));

/// How `serve` was asked to run.
pub struct ServeOptions<'a> {
    pub port: u16,
    /// `Some` exactly when `--ask` was given: the backend to answer
    /// questions through. `None` leaves `POST /api/ask` non-existent.
    pub ask: Option<ProviderChoice<'a>>,
    /// `true` exactly when `--open-code` was given: serve a mapped file's
    /// source at `GET /api/source` (ADR-0013). `false` leaves that route
    /// non-existent, the same pattern as `ask`.
    pub open_code: bool,
}

/// How long the accept loop pauses after a failed accept before trying
/// again. An accept error on loopback is resource exhaustion in practice —
/// EMFILE when the process is out of descriptors — and retrying instantly
/// turns exhaustion into a spinning core: the failed accept leaves the
/// pending connection in the queue, so the next attempt fails the same way
/// (story 20). A tenth of a second is a bounded pause, not a policy — at
/// most ten failed accepts a second cost nothing to notice, and an honest
/// client arriving as the condition clears waits at most this long. A
/// pause, never a retry budget and never a shutdown: the loop keeps
/// accepting the moment an accept succeeds.
const ACCEPT_BACKOFF: Duration = Duration::from_millis(100);

/// Serves the embedded dashboard, `<root>/.codeatlas/knowledge-graph.json`,
/// and — when present — the diff overlay next to it, on 127.0.0.1 until the
/// process is interrupted. Loopback is hardcoded — the listener cannot be
/// pointed at a routable interface (ADR-0006). Port 0 asks the OS for a free
/// port; the actually bound URL is printed to stdout.
///
/// With [`ServeOptions::ask`] set, `POST /api/ask` is served too.
pub fn serve(root: &Path, options: ServeOptions<'_>) -> Result<()> {
    // Before anything else, including the map check: whether this binary can
    // answer questions at all is a property of how it was compiled, and a
    // sealed build should say so rather than get as far as complaining about
    // the repository (ADR-0006, ADR-0009).
    let ask = options
        .ask
        .map(|choice| {
            enrich::resolve_provider(choice)
                .map(SharedProvider::from)
                .context("`serve --ask` needs an enrichment backend")
        })
        .transpose()?;

    let root = root
        .canonicalize()
        .with_context(|| format!("cannot serve {}", root.display()))?;
    let map_path = root.join(OUTPUT_DIR).join("knowledge-graph.json");
    let overlay_path = root.join(OUTPUT_DIR).join(crate::diff::OVERLAY_FILE);
    if !map_path.exists() {
        bail!(
            "no map at {} — run `codeatlas scan {}` first",
            map_path.display(),
            root.display()
        );
    }
    let routes = Routes {
        map_path,
        overlay_path,
        ask,
        source: options.open_code.then(|| root.clone()),
    };

    let port = options.port;
    let listener = TcpListener::bind((Ipv4Addr::LOCALHOST, port)).with_context(|| {
        format!("cannot bind 127.0.0.1:{port} — is the port in use? (--port picks another; 0 lets the OS choose)")
    })?;
    let addr = listener.local_addr()?;
    // The URL goes to stdout so scripts (and the e2e test) can capture it;
    // stdout is line-buffered, so the line is visible before we block.
    println!("CodeAtlas dashboard at http://{addr}/");
    eprintln!("serving {} — press Ctrl-C to stop", root.display());
    if routes.ask.is_some() {
        eprintln!("answering questions at POST http://{addr}{ASK_ROUTE}");
    } else if !enrich::recognised_specs().is_empty() {
        // Without `--ask` the dashboard hides the whole feature — no Ask
        // button, no hint in the search field, no walkthrough step — because
        // `GET /api/capabilities` tells it this server cannot answer, and
        // advertising a question nobody here can answer is worse than saying
        // nothing. That is right in the browser and it leaves a gap: a reader
        // who has only ever run plain `serve` has no way to learn the feature
        // exists at all. This is the place to close it, because this is where
        // `--ask` is something they can act on.
        //
        // Guarded on the compiled backend list and not on a feature name. A
        // sealed build has nothing for `--ask` to resolve, so the pointer
        // would send the reader straight into the startup refusal above — see
        // `recognised_specs`, whose own comment is about this exact mistake.
        // No `cargo test` build can reach that branch, because every one of
        // them carries `test-provider`; `scripts/sealed-probe.sh` checks it
        // against a real sealed binary.
        eprintln!("questions are off; restart with --ask to ask this map questions in prose");
    }
    if routes.source.is_some() {
        // Said out loud because it is a disclosure decision: with this flag
        // any local process may read every mapped file over the port
        // (ADR-0013), and the reader who consented should see what to.
        eprintln!("open code is on: mapped files' source at GET http://{addr}{SOURCE_ROUTE}");
    }

    // Ctrl-C ends the process (default SIGINT handling); nothing to clean up
    // beyond what the OS reclaims. One thread per connection: browsers open
    // parallel connections for assets, and blocking them behind one another
    // stalls first paint.
    for stream in listener.incoming() {
        let stream = match stream {
            Ok(stream) => stream,
            Err(_) => {
                // Backing off is what turns descriptor exhaustion into
                // degraded service instead of a burned core: the CPU goes
                // to the handler threads whose exits will free
                // descriptors, and the loop retries at a human pace
                // rather than a syscall one.
                thread::sleep(ACCEPT_BACKOFF);
                continue;
            }
        };
        let routes = routes.clone();
        thread::spawn(move || {
            // Per-connection errors (client hung up mid-request) only affect
            // that client; the server must outlive them — including when the
            // question backend fails, which is an ordinary response here
            // rather than an end to serving (spec story 14's rule).
            let _ = handle(stream, &routes);
        });
    }
    Ok(())
}

/// The route a question is asked on. One constant because the server prints
/// it, routes on it, and the dashboard fetches it.
pub const ASK_ROUTE: &str = "/api/ask";

/// The route a mapped file's source is fetched on (ADR-0013):
/// `GET /api/source?id=<file-node-id>`, registered only while `--open-code`
/// was given. The id — not a path — is the address, because the map is the
/// allowlist: only a node the map holds resolves, so there is no
/// path-addressed serving to defend.
pub const SOURCE_ROUTE: &str = "/api/source";

/// Where the dashboard reads what this server process can do. Two fields —
/// whether [`ASK_ROUTE`] exists, and whether [`SOURCE_ROUTE`] does —
/// because those are the things the page cannot work out for itself: it is
/// the same build either way, and the alternative to being told is probing
/// routes to see which exist. The absence this route reports is also how a
/// share artifact inherits having no open-code affordance at all: no server
/// answers it there, so the capability reads as off (ADR-0013).
pub const CAPABILITIES_ROUTE: &str = "/api/capabilities";

/// What answers one registered route — the dispatch half of a [`REGISTRY`]
/// entry, kept apart so each entry stays one readable line of facts.
#[derive(Clone, Copy, PartialEq, Eq)]
enum Endpoint {
    /// The map JSON, read from disk per request.
    Map,
    /// The diff overlay, optional on disk.
    Diff,
    /// Two booleans about this process: whether [`ASK_ROUTE`] and
    /// [`SOURCE_ROUTE`] are registered.
    Capabilities,
    /// A question, answered through the provider `--ask` resolved.
    Ask,
    /// A mapped file's source, read live from disk (ADR-0013).
    Source,
}

/// One route this server answers: the request line that selects it, and the
/// endpoint that answers it. The fields a request is matched on are public
/// so `tests/routes.rs` can derive the served surface from the same table
/// [`handle`] walks; the struct cannot be built outside this module, so the
/// registry stays closed.
pub struct Route {
    pub method: &'static str,
    pub path: &'static str,
    endpoint: Endpoint,
}

/// Every route this server can answer, and the only place one is declared:
/// [`handle`] dispatches by walking this slice, so a route absent from it is
/// not served at all — the code and the route list are the same thing, which
/// is what lets `tests/routes.rs` hold `docs/SECURITY.md` to naming every
/// entry (V2 story 17; deferred ticket 36, the registry chosen over a source
/// scanner because a scanner that recognises a spelling convention cannot
/// fail for a route spelled unexpectedly).
///
/// [`ASK_ROUTE`] and [`SOURCE_ROUTE`] are the two conditional entries:
/// [`Routes::route`] registers each only while its flag put something
/// behind it, so without `--ask` or `--open-code` the route does not exist
/// rather than existing and refusing — a plain `serve` still answers the
/// POST with the same 405 as any other non-GET, and a source GET with the
/// same 404 as any path nobody serves.
///
/// Deliberately not in this table: the embedded-asset fallback. A GET whose
/// path is registered nowhere is looked up in `ASSETS` and 404s when it is
/// not there — that is the dashboard itself, every remaining path rather
/// than a route with one of its own, and `docs/SECURITY.md` states it
/// separately.
///
/// HEAD is not in this table either, and is still answered wherever GET is
/// (story 19): [`handle`] routes a HEAD through the GET entries and
/// withholds the body at the end (RFC 9110 §9.3.2), so the derivation
/// cannot drift from a second list — there is no second list.
pub const REGISTRY: &[Route] = &[
    Route {
        method: "GET",
        path: "/api/map",
        endpoint: Endpoint::Map,
    },
    Route {
        method: "GET",
        path: "/api/diff",
        endpoint: Endpoint::Diff,
    },
    Route {
        method: "GET",
        path: CAPABILITIES_ROUTE,
        endpoint: Endpoint::Capabilities,
    },
    Route {
        method: "POST",
        path: ASK_ROUTE,
        endpoint: Endpoint::Ask,
    },
    Route {
        method: "GET",
        path: SOURCE_ROUTE,
        endpoint: Endpoint::Source,
    },
];

/// What a connection may be answered from. Cloned per connection: two
/// paths and, when `--ask` was given, a shared handle on the provider.
#[derive(Clone)]
struct Routes {
    map_path: PathBuf,
    overlay_path: PathBuf,
    /// Present exactly when `serve --ask` was given. `None` is what keeps
    /// the ask entry out of the registry ([`Routes::route`]), which is what
    /// makes `POST /api/ask` a 405 like any other non-GET: the route does
    /// not exist rather than existing and refusing.
    ask: Option<SharedProvider>,
    /// The repository root, present exactly when `serve --open-code` was
    /// given — the same pattern as `ask`: `None` keeps the source entry out
    /// of the registry, so without the flag `GET /api/source` falls to the
    /// asset lookup and 404s like any path nobody serves (ADR-0013).
    source: Option<PathBuf>,
}

impl Routes {
    /// The [`REGISTRY`] as this server runs it: the entry matching the
    /// request line, if what backs it exists. Two conditions today — the
    /// ask entry needs the provider `--ask` resolved, the source entry the
    /// root `--open-code` kept — and they live here so the table above
    /// stays a plain list of facts.
    fn route(&self, method: &str, path: &str) -> Option<&'static Route> {
        REGISTRY.iter().find(|route| {
            route.method == method
                && route.path == path
                && (route.endpoint != Endpoint::Ask || self.ask.is_some())
                && (route.endpoint != Endpoint::Source || self.source.is_some())
        })
    }

    /// The `Allow` value a 405 at `path` must carry — exactly the methods
    /// served there, which RFC 9110 §15.5.6 makes a MUST on every 405.
    /// GET and HEAD open the list because every path answers them: GET
    /// through the registry or the embedded-asset fallback, HEAD wherever
    /// GET is (both above). The walk over [`REGISTRY`] then adds each
    /// remaining method *as this server runs it*, through [`Routes::route`]
    /// so the flag conditions apply: a route a flag left unregistered is
    /// not served, and naming its method here would be the capability
    /// route's lie in header form. Today that adds POST at [`ASK_ROUTE`]
    /// exactly while `--ask` holds it registered, and nothing anywhere
    /// else — derived, not listed, so a route added later is covered
    /// without anyone remembering this line.
    fn allow(&self, path: &str) -> String {
        let mut allow = String::from("GET, HEAD");
        for route in REGISTRY {
            if route.path == path
                && !matches!(route.method, "GET" | "HEAD")
                && self.route(route.method, path).is_some()
            {
                allow.push_str(", ");
                allow.push_str(route.method);
            }
        }
        allow
    }
}

/// The request methods HTTP itself defines: RFC 9110 §9.3's eight, plus
/// PATCH (RFC 5789). The refusal taxonomy turns on this list (V3 story 19),
/// because the two refusals answer different questions and a stranger's
/// tooling reads them differently: a method ON this list that no route at
/// the requested path serves draws a 405 whose `Allow` names what is
/// served — "the method exists here, just not at this path" — while a
/// method OFF it draws a 501, "this server does not implement the method
/// at all", which is what RFC 9110 §9.1 prescribes for a method the server
/// does not recognise. Before V3 a `FROB` drew the 405, claiming a
/// method-of-this-path problem the request did not have; V2 ticket 13
/// recorded that as its residual and this list is what retires it. HTTP's
/// extension registries (WebDAV and kin) are deliberately not here: on a
/// loopback dashboard that serves two methods, "recognised" means the
/// methods HTTP's own core standards define, and anything beyond them is
/// honestly not implemented.
const RECOGNISED_METHODS: &[&str] = &[
    "GET", "HEAD", "POST", "PUT", "DELETE", "CONNECT", "OPTIONS", "TRACE", "PATCH",
];

/// How long a handler thread waits on a read before giving up on the
/// connection. Generous for a loopback client, but finite: a client that
/// connects and never finishes its request must not park a thread forever.
const READ_TIMEOUT: Duration = Duration::from_secs(10);

/// Per-connection socket setup: every accepted stream gets [`READ_TIMEOUT`]
/// so a half-open request errors out instead of blocking its thread
/// indefinitely.
fn prepare(stream: TcpStream) -> std::io::Result<TcpStream> {
    stream.set_read_timeout(Some(READ_TIMEOUT))?;
    Ok(stream)
}

/// How long a whole request may take to arrive — request line, header block
/// and, on the one route that reads one, the body. [`READ_TIMEOUT`] is per
/// read, and a per-read timeout bounds no request: any number of reads that
/// each beat it add up to no limit at all, so a client trickling one header
/// line every few seconds held a handler thread for as long as it cared to
/// (deferred V1 ticket 38). Twice [`READ_TIMEOUT`], so the per-read guard
/// keeps its own job — a client that goes quiet is dropped by it at ten
/// seconds, half of this deadline — and twenty seconds is a geological age
/// for a request an honest loopback client completes in microseconds.
const REQUEST_DEADLINE: Duration = Duration::from_secs(20);

/// The most bytes one line of a request head may carry — the request line
/// or one header line. Without a cap, a client sending one endless line
/// grows a buffer for as long as [`REQUEST_DEADLINE`] runs; with one, the
/// line is refused the moment it passes the cap. 8 KiB is the head-line
/// ceiling Apache and nginx default to, and the two headers this server
/// keeps ([`Headers`]) fit an honest line in under a hundred bytes.
const MAX_HEADER_LINE: usize = 8 * 1024;

/// The most header lines one request may carry. A browser sends a dozen or
/// two; a client past sixty-four is not describing a request, it is testing
/// how long this server will listen — and the answer must be a number.
const MAX_HEADER_LINES: usize = 64;

/// The most bytes a request body may carry. A question is a sentence in a
/// small JSON object; anything larger is a mistake or an attempt to make a
/// hand-rolled server allocate on demand.
const MAX_BODY: usize = 64 * 1024;

/// The most a connection is read out on the way to being closed. Closing on
/// bytes nobody read resets the connection in the client's face (see
/// [`hang_up`]), but past a megabyte of them being tidy is not worth the
/// bytes: a caller still sending after it has been answered has had its
/// answer.
///
/// Its own number rather than a multiple of [`MAX_BODY`]. The two cap
/// different things and no longer move together: `MAX_BODY` bounds a body
/// this server parses, and that read is bounded above it by the 413 check in
/// [`answer_question`], while this bounds bytes nobody will ever look at, on
/// the way out of a connection that has already been answered.
const MAX_DRAIN: usize = 1024 * 1024;

/// How long [`hang_up`] waits on a client that has gone quiet mid-send. Much
/// shorter than [`READ_TIMEOUT`], and it can be: by then the response has
/// been written and flushed, so nothing the reader is waiting for depends on
/// this number.
const LINGER_TIMEOUT: Duration = Duration::from_millis(500);

/// How long [`hang_up`] may take in total, across every read it makes.
///
/// This is the bound that can be stated, and [`LINGER_TIMEOUT`] is not: a
/// per-read timeout bounds no loop, because any number of reads that each
/// beat it add up to no limit at all. A client dribbling one byte every
/// 450 ms leaves every read inside `LINGER_TIMEOUT` and still takes
/// [`MAX_DRAIN`] of them to stop — days of thread life, unauthenticated, on
/// every route. A deadline across the whole loop is what makes a handler
/// thread's extra life a number rather than a hope.
const DRAIN_DEADLINE: Duration = Duration::from_secs(1);

/// The two request headers this server reads. It read none before ADR-0009,
/// and reads exactly these now — one to frame a body, one to refuse a
/// request no honest client would send (see [`answer_question`]).
#[derive(Default)]
struct Headers {
    content_length: usize,
    content_type: String,
}

/// Arms the socket for one read inside the whole-request deadline: at most
/// the time left until it, never more than [`READ_TIMEOUT`] of that, and
/// returns the timeout armed so the caller can tell which guard a timeout
/// then belongs to. `None` when the budget is already spent — or when it
/// would not go onto the socket, the same refusal-to-hope as [`hang_up`]'s:
/// the deadline is only consulted between reads, so a stream left on the
/// ten-second timeout could overshoot the bound this file states.
fn arm(stream: &TcpStream, deadline: Instant) -> Option<Duration> {
    let left = deadline.saturating_duration_since(Instant::now());
    if left.is_zero() {
        return None;
    }
    let wait = left.min(READ_TIMEOUT);
    stream.set_read_timeout(Some(wait)).ok()?;
    Some(wait)
}

/// Whether a read failed by running out the timeout [`arm`] set rather than
/// by the connection dying. Unix reports an armed timeout as `WouldBlock`,
/// Windows as `TimedOut`; both mean the same silence.
fn timed_out(err: &std::io::Error) -> bool {
    matches!(
        err.kind(),
        std::io::ErrorKind::WouldBlock | std::io::ErrorKind::TimedOut
    )
}

/// One line of a request head, or the bound that cut it short.
enum HeadLine {
    /// A complete line, terminator still attached — or whatever had arrived
    /// when the peer sent EOF, empty included — exactly as `read_line` used
    /// to hand it over, so the caller's blank-line and end-of-stream checks
    /// read unchanged.
    Line(String),
    /// The line passed [`MAX_HEADER_LINE`] without ending.
    OverLong,
    /// [`REQUEST_DEADLINE`] ran out while the line was still arriving.
    PastDeadline,
    /// The line holds bytes that are not UTF-8 — malformed, not over-bound:
    /// a request head is text by the protocol's own grammar, and `String`
    /// is how everything downstream reads it.
    NotUtf8,
}

/// Reads one line of the request head under two of the three bounds: at
/// most [`MAX_HEADER_LINE`] bytes, inside [`REQUEST_DEADLINE`]. One
/// `fill_buf` at a time so the cap is enforced *while* the line arrives —
/// `read_line` would grow its `String` for as long as the peer withheld the
/// newline, which is exactly the defect this replaces.
///
/// A timeout inside the armed wait is the deadline's refusal when the wait
/// was clamped below [`READ_TIMEOUT`], and the per-read guard's plain I/O
/// error — a dropped connection, no response, the behaviour that guard has
/// always had — when it was not.
fn head_line(reader: &mut BufReader<TcpStream>, deadline: Instant) -> std::io::Result<HeadLine> {
    let mut line = Vec::new();
    loop {
        let Some(wait) = arm(reader.get_ref(), deadline) else {
            return Ok(HeadLine::PastDeadline);
        };
        let buffered = match reader.fill_buf() {
            Ok(buffered) => buffered,
            Err(err) if timed_out(&err) && wait < READ_TIMEOUT => {
                return Ok(HeadLine::PastDeadline);
            }
            Err(err) => return Err(err),
        };
        if buffered.is_empty() {
            break; // EOF: hand back the partial line, as `read_line` did.
        }
        let newline = buffered.iter().position(|&byte| byte == b'\n');
        let take = newline.map_or(buffered.len(), |at| at + 1);
        if line.len() + take > MAX_HEADER_LINE {
            return Ok(HeadLine::OverLong);
        }
        line.extend_from_slice(&buffered[..take]);
        reader.consume(take);
        if newline.is_some() {
            break;
        }
    }
    Ok(String::from_utf8(line).map_or(HeadLine::NotUtf8, HeadLine::Line))
}

/// What reading a request head produced: a request to route, or the refusal
/// that ends it. Three bounds, three separate failures — never one "request
/// too large" condition, because the reader of a refusal wants to know which
/// bound tripped. The malformed lane (story 19) rides the same refusal
/// shape but is not a bound: a head that is not text draws a 400 naming
/// the fault in the request, where the 408 and the 431s name a limit of
/// this server's. The per-read timeout is deliberately not represented here:
/// its failure stays what it always was, an I/O error and a silently dropped
/// connection, because a client that went quiet is not reading refusals.
enum Head {
    /// The request line and the two headers this server keeps.
    Complete {
        request_line: String,
        headers: Headers,
    },
    /// The bound that tripped: response status, and the sentence naming it.
    Refused {
        status: &'static str,
        reason: String,
    },
}

/// [`REQUEST_DEADLINE`]'s refusal. 408 is HTTP's own word for it — "the
/// server did not receive a complete request within the time it was
/// prepared to wait" — and it is sent as a real response rather than a bare
/// close because [`respond`]'s hang-up keeps even a refused trickler's
/// remaining hold on the thread bounded.
fn past_deadline() -> Head {
    Head::Refused {
        status: "408 Request Timeout",
        reason: deadline_reason(),
    }
}

/// The sentence both 408s carry — the head's, above, and the body read's in
/// [`answer_question`], which answers in that route's JSON error shape.
fn deadline_reason() -> String {
    format!(
        "the whole request must arrive within {} seconds",
        REQUEST_DEADLINE.as_secs()
    )
}

/// The malformed lane's refusal for a head that is not text (story 19): a
/// 400 with the reason, where this used to be an I/O error and a silently
/// closed connection the client could only report as a network failure.
/// 400 is HTTP's word for "the fault is in the request" — deliberately not
/// a 431, because nothing here is over any bound.
fn not_utf8() -> Head {
    Head::Refused {
        status: "400 Bad Request",
        reason: "the request head is not valid UTF-8".into(),
    }
}

/// [`MAX_HEADER_LINE`]'s refusal. 431 is the status RFC 6585 provides for a
/// header block a server will not hold — for one oversized field and for an
/// oversized total alike, with the response saying which; here the sentence
/// names this cap and [`read_head`]'s count refusal names that one. The
/// request line rides the same cap and draws the same refusal: it is the
/// first line of the head, and a second status for the same bound on a
/// different line would be a fourth failure for three bounds.
fn over_long_line() -> Head {
    Head::Refused {
        status: "431 Request Header Fields Too Large",
        reason: format!("a header line may be at most {MAX_HEADER_LINE} bytes"),
    }
}

/// Consumes the request line and header block under the three bounds —
/// [`REQUEST_DEADLINE`] across every read, [`MAX_HEADER_LINE`] per line,
/// [`MAX_HEADER_LINES`] on the count — keeping only what [`handle`] routes
/// on. An unparseable content length reads as no body, and the route that
/// wanted one rejects the empty request on its own terms.
fn read_head(reader: &mut BufReader<TcpStream>, deadline: Instant) -> std::io::Result<Head> {
    let request_line = match head_line(reader, deadline)? {
        HeadLine::Line(line) => line,
        HeadLine::OverLong => return Ok(over_long_line()),
        HeadLine::PastDeadline => return Ok(past_deadline()),
        HeadLine::NotUtf8 => return Ok(not_utf8()),
    };
    let mut headers = Headers::default();
    let mut lines = 0usize;
    loop {
        let line = match head_line(reader, deadline)? {
            HeadLine::Line(line) => line,
            HeadLine::OverLong => return Ok(over_long_line()),
            HeadLine::PastDeadline => return Ok(past_deadline()),
            HeadLine::NotUtf8 => return Ok(not_utf8()),
        };
        if line.is_empty() || line == "\r\n" || line == "\n" {
            return Ok(Head::Complete {
                request_line,
                headers,
            });
        }
        lines += 1;
        if lines > MAX_HEADER_LINES {
            return Ok(Head::Refused {
                status: "431 Request Header Fields Too Large",
                reason: format!("a request may carry at most {MAX_HEADER_LINES} header lines"),
            });
        }
        let Some((name, value)) = line.split_once(':') else {
            continue;
        };
        let value = value.trim();
        if name.eq_ignore_ascii_case("content-length") {
            headers.content_length = value.parse().unwrap_or(0);
        } else if name.eq_ignore_ascii_case("content-type") {
            headers.content_type = value.to_ascii_lowercase();
        }
    }
}

/// Answers one request and closes the connection (`Connection: close` — the
/// dashboard is a handful of requests, keep-alive buys nothing but state).
fn handle(stream: TcpStream, routes: &Routes) -> std::io::Result<()> {
    // The whole-request clock starts before the first byte is read: the
    // deadline is the bound a per-read timeout is not, a total.
    let deadline = Instant::now() + REQUEST_DEADLINE;
    let mut reader = BufReader::new(prepare(stream)?);
    let (request_line, headers) = match read_head(&mut reader, deadline)? {
        Head::Complete {
            request_line,
            headers,
        } => (request_line, headers),
        Head::Refused { status, reason } => {
            let mut stream = reader.into_inner();
            return respond(&mut stream, status, "text/plain", reason.as_bytes());
        }
    };

    // The malformed lane's other half (V2 story 19, completed by V3 story
    // 19): a request line that does not parse as HTTP/1.1's own grammar —
    // method, target, `HTTP/` version, and NOTHING after the version —
    // draws a 400 naming the shape, never a silent close and never silent
    // tolerance. The fourth `parts.next()` is the strictness V2 left as a
    // residual: `GET / HTTP/1.1 junk` used to be served as if the junk
    // were not there, and a grammar is three tokens or it is not that
    // grammar. Size and pace are not malformed and stay in their own
    // lanes: the 408 and the 431s above, decided before this line is
    // looked at.
    let mut parts = request_line.split_whitespace();
    let (method, target) = match (parts.next(), parts.next(), parts.next(), parts.next()) {
        (Some(m), Some(t), Some(v), None) if v.starts_with("HTTP/") => {
            (m.to_string(), t.to_string())
        }
        _ => {
            let mut stream = reader.into_inner();
            return respond(
                &mut stream,
                "400 Bad Request",
                "text/plain",
                b"malformed request line: a request is `<method> <target> HTTP/<version>`",
            );
        }
    };
    let path = target.split(['?', '#']).next().unwrap_or(&target);
    // The query string, kept apart from the path the registry matches on:
    // one route reads one parameter from it ([`source_envelope`]), and every
    // other endpoint ignores it exactly as before.
    let query = target
        .split('#')
        .next()
        .unwrap_or(&target)
        .split_once('?')
        .map(|(_, query)| query);

    // The whole surface is one lookup: [`REGISTRY`] filtered by what this
    // server actually holds. Everything below is what the found entry says.
    // HEAD is answered wherever GET is (story 19), so it is routed *as* a
    // GET: the registry's GET entries are the definition of "wherever GET
    // is", and looking HEAD up through them is what keeps the derivation
    // free of a second hand-maintained list. All that differs is the body
    // withheld at the very end.
    let head_only = method == "HEAD";
    let route = routes.route(if head_only { "GET" } else { &method }, path);

    // The one non-GET route, and only when `--ask` put a backend behind it —
    // otherwise `routes.route` never registered it. Reading a body is
    // confined to this branch on purpose: without `--ask` the server ignores
    // one exactly as it did before ADR-0009, so its behaviour on every other
    // route is unchanged rather than merely similar. It keeps the buffered
    // reader for that body; every other endpoint answers on the bare stream.
    if let Some(Route {
        endpoint: Endpoint::Ask,
        ..
    }) = route
        && let Some(provider) = &routes.ask
    {
        return answer_question(reader, routes, provider.as_ref(), &headers, deadline);
    }

    let mut stream = reader.into_inner();
    if method != "GET" && !head_only {
        // The taxonomy's first fork ([`RECOGNISED_METHODS`]): a method HTTP
        // itself never defined gets the 501 RFC 9110 §9.1 prescribes, not a
        // 405 claiming the problem is this path — there is no path on this
        // server, or any other, where `FROB` would have fared better. No
        // `Allow` on it for the same reason: that header answers "what does
        // this path serve", which is the 405's question below.
        if !RECOGNISED_METHODS.contains(&method.as_str()) {
            return respond(
                &mut stream,
                "501 Not Implemented",
                "text/plain",
                format!("{method} is not a method this server implements").as_bytes(),
            );
        }
        // Build-aware, because with `--ask` the flat claim is false — and a
        // reader who mistyped the question route deserves to be told the
        // right one rather than that POST is unsupported. HEAD skips this
        // lane entirely: it is a method this server *answers*, not one it
        // refuses more politely (the V2 ticket 13 note). The sentences are
        // the human half; the machine half is the `Allow` header RFC 9110
        // §15.5.6 makes a MUST on every 405, naming exactly the methods
        // served at this path ([`Routes::allow`]) — added by V3's protocol
        // honesties, which deliberately superseded V2 ticket 13's
        // byte-identical-405s pin to do it.
        let served: &[u8] = match routes.ask {
            Some(_) => b"only GET, and POST /api/ask, are served",
            None => b"only GET is served",
        };
        return respond_method_not_allowed(&mut stream, &routes.allow(path), served);
    }

    // What GET would answer: status, content type, body. Built whole even
    // for a HEAD, because the headers HEAD promises are the ones GET would
    // have sent — RFC 9110 §9.3.2 wants Content-Length to be GET's, and a
    // length invented without the body in hand is exactly the number that
    // drifts. The cost is a disk read this server already pays on every
    // GET of the same route.
    let (status, content_type, body): (&str, &str, Cow<'_, [u8]>) =
        match route.map(|route| route.endpoint) {
            Some(Endpoint::Map) => {
                // Read from disk per request so a re-scan shows up on refresh.
                match std::fs::read(&routes.map_path) {
                    Ok(map) => ("200 OK", "application/json", map.into()),
                    Err(_) => (
                        "404 Not Found",
                        "application/json",
                        format!(
                            "{{\"error\":\"no map at {} — run `codeatlas scan` first\"}}",
                            routes.map_path.display()
                        )
                        .into_bytes()
                        .into(),
                    ),
                }
            }
            Some(Endpoint::Capabilities) => (
                // Always 200, always answered, in every build: an absent
                // route and a route saying "no" would be two ways to express
                // one fact, and the client would have to treat them the same
                // anyway.
                "200 OK",
                "application/json",
                format!(
                    "{{\"ask\":{},\"open_code\":{}}}",
                    routes.ask.is_some(),
                    routes.source.is_some()
                )
                .into_bytes()
                .into(),
            ),
            Some(Endpoint::Diff) => {
                // The overlay is optional: absent means `codeatlas diff` has
                // not run, and the dashboard hides its toggle on the 404.
                match std::fs::read(&routes.overlay_path) {
                    Ok(overlay) => ("200 OK", "application/json", overlay.into()),
                    Err(_) => (
                        "404 Not Found",
                        "application/json",
                        Cow::Borrowed(
                            &b"{\"error\":\"no diff overlay - run `codeatlas diff` first\"}"[..],
                        ),
                    ),
                }
            }
            Some(Endpoint::Source) => match &routes.source {
                // The one route that reads the query string: the id names a
                // file node, the map is the allowlist, and the path read is
                // the node's own — never the request's (ADR-0013).
                Some(root) => source_envelope(root, &routes.map_path, query),
                // Unreachable — [`Routes::route`] never selects this entry
                // without a root behind it — but the type cannot say so,
                // and the honest answer if it ever did is the one an
                // unregistered GET draws from the asset lookup below.
                None => (
                    "404 Not Found",
                    "text/plain",
                    Cow::Borrowed(&b"not found"[..]),
                ),
            },
            // No registered route: the embedded dashboard answers every
            // remaining GET, 404 when it holds no such asset. `Ask` cannot
            // in fact arrive here — it is registered for POST alone, and
            // POST left at the 405 — but falling to the asset lookup is also
            // the honest meaning of "no GET route by that name exists".
            // A HEAD of the ask route lands here as `None` for the same
            // reason and draws the 404 `GET /api/ask` has always drawn:
            // HEAD mirrors GET even where GET is not served.
            Some(Endpoint::Ask) | None => {
                let asset_path = match path.trim_start_matches('/') {
                    "" => "index.html",
                    rest => rest,
                };
                match ASSETS.iter().find(|a| a.path == asset_path) {
                    Some(asset) => ("200 OK", asset.content_type, Cow::Borrowed(asset.bytes)),
                    None => (
                        "404 Not Found",
                        "text/plain",
                        Cow::Borrowed(&b"not found"[..]),
                    ),
                }
            }
        };
    if head_only {
        respond_head(&mut stream, status, content_type, &body)
    } else {
        respond(&mut stream, status, content_type, &body)
    }
}

/// The request body `POST /api/ask` accepts: the question, and optionally
/// the conversation so far (ADR-0012). `turns` defaults to empty, so a bare
/// `{"question": …}` — every client that existed before conversations did —
/// remains a valid request, answered exactly as before.
///
/// The turns are input to clamp, never grounds to refuse: the bounds and
/// their enforcement live in `ask::build` beside the question's own, and the
/// wire shape's TypeScript half is `dashboard/src/app/ask.ts` (held in step
/// by `tests/routes.rs`). Malformed JSON and a wrong `Content-Type` keep
/// their existing rejections — clamping is for over-bound, well-formed
/// input.
#[derive(serde::Deserialize)]
struct AskBody {
    question: String,
    #[serde(default)]
    turns: Vec<ask::Turn>,
}

/// The content type a question must be sent as.
///
/// Not politeness — it is what stops an arbitrary web page in the reader's
/// browser from spending their model budget while `serve --ask` is running.
/// A cross-origin `fetch` or form post can only set the three "simple"
/// content types without a CORS preflight; demanding this one forces a
/// preflight, and this server answers no `OPTIONS`, so the browser never
/// sends the request. Same-origin callers — the dashboard, ticket 27 — are
/// unaffected, and `curl` simply sets the header.
const ASK_CONTENT_TYPE: &str = "application/json";

/// Answers one question, or explains why it cannot. Every outcome is a
/// response: a failing backend must not take the server down with it, which
/// is spec story 14's rule applied to a route rather than to a scan.
///
/// The statuses distinguish who can fix the problem. A question that is
/// blank, over-long, or not JSON is a 400 the reader can act on; a backend
/// that would not answer is a 502, because nothing about the request was
/// wrong.
fn answer_question(
    mut reader: BufReader<TcpStream>,
    routes: &Routes,
    provider: &dyn EnrichmentProvider,
    headers: &Headers,
    deadline: Instant,
) -> std::io::Result<()> {
    // Both of these are settled by the header block, so they are settled
    // before a byte of the body is read: an over-long request costs this
    // process nothing but the bytes already in flight, and a request from
    // another origin costs it nothing at all. Answering while a body is
    // still arriving is safe because [`respond`] hangs the connection up
    // rather than dropping it on the unread remainder.
    if headers.content_length > MAX_BODY {
        return json_error(
            &mut reader.into_inner(),
            "413 Payload Too Large",
            &format!("the request body may be at most {MAX_BODY} bytes"),
        );
    }
    if !headers.content_type.starts_with(ASK_CONTENT_TYPE) {
        return json_error(
            &mut reader.into_inner(),
            "415 Unsupported Media Type",
            &format!("questions must be sent as {ASK_CONTENT_TYPE}"),
        );
    }

    // The only body this server reads. The 413 above bounds it in bytes;
    // [`REQUEST_DEADLINE`] bounds it in time, because a declared length
    // under the cap says nothing about when the bytes come — a body
    // dribbled one read at a time beats the per-read timeout on every one
    // of them, exactly as a trickled header block does.
    let body = match read_body(&mut reader, headers.content_length, deadline)? {
        Some(body) => body,
        None => {
            return json_error(
                &mut reader.into_inner(),
                "408 Request Timeout",
                &deadline_reason(),
            );
        }
    };
    let stream = &mut reader.into_inner();

    let asked = match serde_json::from_slice::<AskBody>(&body) {
        Ok(asked) => asked,
        Err(err) => {
            // The hint states the whole accepted shape: ticket 08 grew the
            // body an optional `turns` array, and a 400 describing only the
            // bare form would send the one client this message exists for —
            // someone hand-writing a request — back to a shape that cannot
            // carry a conversation.
            return json_error(
                stream,
                "400 Bad Request",
                &format!(
                    "the body must be JSON of the form {{\"question\": \"…\"}}, optionally \
                     with \"turns\": previous {{\"question\", \"answer\", \"citations\"}} \
                     objects, oldest first: {err}"
                ),
            );
        }
    };

    // Re-read per request, exactly as `/api/map` does, so a re-scan while
    // the server runs is answered against the new map.
    let graph = match read_graph(&routes.map_path) {
        Ok(graph) => graph,
        Err(err) => {
            return json_error(
                stream,
                "500 Internal Server Error",
                &format!(
                    "cannot read the map at {}: {err:#}",
                    routes.map_path.display()
                ),
            );
        }
    };

    let question = match ask::build(&graph, &asked.question, &asked.turns) {
        Ok(question) => question,
        Err(err) => return json_error(stream, "400 Bad Request", &format!("{err:#}")),
    };
    match ask::answer(provider, &question) {
        Ok(answer) => {
            let mut payload = serde_json::json!({
                "answer": answer.text,
                "citations": answer.citations,
            });
            // Present exactly when the backend's envelope reported it
            // (ADR-0012): a backend that reports nothing produces no field
            // at all, so the dashboard's absent display is the wire's own
            // absence rather than a rendering of zero.
            if let Some(usage) = answer.usage {
                payload["usage"] = serde_json::json!(usage);
            }
            respond(
                stream,
                "200 OK",
                "application/json",
                payload.to_string().as_bytes(),
            )
        }
        Err(err) => json_error(stream, "502 Bad Gateway", &format!("{err:#}")),
    }
}

/// Reads the declared body inside what is left of the whole-request
/// deadline: `None` when [`REQUEST_DEADLINE`] ran out first, for the caller
/// to refuse. A body shorter than declared ends at EOF exactly as the old
/// `take`-based read did — that is the JSON parser's 400 to hand out, not
/// an I/O failure. The caller has already checked `length` against
/// [`MAX_BODY`], so the allocation here is bounded by that check.
fn read_body(
    reader: &mut BufReader<TcpStream>,
    length: usize,
    deadline: Instant,
) -> std::io::Result<Option<Vec<u8>>> {
    let mut body = vec![0u8; length];
    let mut filled = 0;
    while filled < body.len() {
        let Some(wait) = arm(reader.get_ref(), deadline) else {
            return Ok(None);
        };
        match reader.read(&mut body[filled..]) {
            Ok(0) => break,
            Ok(read) => filled += read,
            Err(err) if timed_out(&err) && wait < READ_TIMEOUT => return Ok(None),
            Err(err) => return Err(err),
        }
    }
    body.truncate(filled);
    Ok(Some(body))
}

fn read_graph(map_path: &Path) -> anyhow::Result<KnowledgeGraph> {
    Ok(serde_json::from_slice(&std::fs::read(map_path)?)?)
}

/// The most bytes of one file's source the envelope carries. Past it the
/// source arrives cut at this cap with the envelope's `truncated` flag set —
/// disclosed, never refused (ADR-0013): a truncated *question* is silently a
/// different question, but a truncated *display* that says so is honest, and
/// most of a large file's value is at its top. Half a mebibyte is far past
/// what a reader scrolls in a panel, and it keeps what one loopback GET can
/// make this server read and serialize a number rather than the largest
/// file the map happens to hold.
const MAX_SOURCE_BYTES: usize = 512 * 1024;

/// Answers `GET /api/source?id=<file-node-id>` (ADR-0013). The map is the
/// allowlist: the id must name a node the map holds whose kind is `file`,
/// and the path read is that node's own — never anything from the request —
/// so an unmapped path, a symbol id, and a traversal-shaped id all draw the
/// same 404 without the filesystem being looked at. The map is re-read per
/// request, exactly as `/api/map` reads it, and so is the file: an edited
/// file serves its current contents, a deleted one draws an honest 404
/// rather than fabricating source from a stale map.
fn source_envelope(
    root: &Path,
    map_path: &Path,
    query: Option<&str>,
) -> (&'static str, &'static str, Cow<'static, [u8]>) {
    fn json(
        status: &'static str,
        body: serde_json::Value,
    ) -> (&'static str, &'static str, Cow<'static, [u8]>) {
        (
            status,
            "application/json",
            Cow::Owned(body.to_string().into_bytes()),
        )
    }

    let Some(id) = query.and_then(|query| query_param(query, "id")) else {
        return json(
            "400 Bad Request",
            serde_json::json!({
                "error": format!(
                    "the request must name a file node: GET {SOURCE_ROUTE}?id=file:<path>"
                )
            }),
        );
    };
    let graph = match read_graph(map_path) {
        Ok(graph) => graph,
        Err(err) => {
            return json(
                "500 Internal Server Error",
                serde_json::json!({
                    "error": format!("cannot read the map at {}: {err:#}", map_path.display())
                }),
            );
        }
    };
    let Some(node) = graph
        .nodes
        .iter()
        .find(|node| node.kind == NodeKind::File && node.id.as_str() == id)
    else {
        return json(
            "404 Not Found",
            serde_json::json!({
                "error": format!(
                    "{id} is not a file node in the map — the map is the allowlist, \
                     and only mapped files are served"
                )
            }),
        );
    };
    let bytes = match std::fs::read(root.join(&node.path)) {
        Ok(bytes) => bytes,
        Err(_) => {
            return json(
                "404 Not Found",
                serde_json::json!({
                    "error": format!(
                        "{} is in the map but no longer on disk — re-run `codeatlas scan` \
                         for a map that says so",
                        node.path
                    )
                }),
            );
        }
    };
    let truncated = bytes.len() > MAX_SOURCE_BYTES;
    // The clip runs first and highlighting runs on the clipped text, so a
    // truncated file arrives highlighted exactly as served — the notice
    // (`truncated`) is about the same bytes the spans are.
    let served = String::from_utf8_lossy(clip(&bytes));
    let highlighted = crate::highlight::highlight(&node.path, &served);
    json(
        "200 OK",
        serde_json::json!({
            "html": highlighted.html,
            "language": highlighted.language,
            "path": node.path,
            "truncated": truncated,
        }),
    )
}

/// The served prefix of a file's bytes: everything up to
/// [`MAX_SOURCE_BYTES`], backed off past a split UTF-8 sequence so the cut
/// cannot invent a replacement character at the end of an honest file. At
/// most three continuation bytes are stepped over — a UTF-8 scalar is at
/// most four bytes — so the backoff is bounded whatever the bytes hold.
fn clip(bytes: &[u8]) -> &[u8] {
    if bytes.len() <= MAX_SOURCE_BYTES {
        return bytes;
    }
    let mut end = MAX_SOURCE_BYTES;
    while end > MAX_SOURCE_BYTES - 3 && (bytes[end] & 0b1100_0000) == 0b1000_0000 {
        end -= 1;
    }
    &bytes[..end]
}

/// The value of one `key=value` pair in a query string, percent-decoded.
/// Decoding is the minimum an honest client needs — a node id contains `:`
/// and `/`, and `encodeURIComponent` escapes both. `+` stays itself: that
/// is form encoding's space, and a path may honestly carry a plus.
fn query_param(query: &str, name: &str) -> Option<String> {
    query.split('&').find_map(|pair| {
        let (key, value) = pair.split_once('=')?;
        (key == name).then(|| percent_decode(value))
    })
}

/// `%XX` unescaping; anything that is not a full escape — a bare `%`, a
/// short or non-hex tail — passes through as itself. Bytes that decode to
/// invalid UTF-8 read lossily, which can only fail the map lookup: every id
/// the map holds is valid UTF-8 already.
fn percent_decode(value: &str) -> String {
    let bytes = value.as_bytes();
    let mut decoded = Vec::with_capacity(bytes.len());
    let mut at = 0;
    while at < bytes.len() {
        let unescaped = (bytes[at] == b'%')
            .then(|| value.get(at + 1..at + 3))
            .flatten()
            .and_then(|hex| u8::from_str_radix(hex, 16).ok());
        match unescaped {
            Some(byte) => {
                decoded.push(byte);
                at += 3;
            }
            None => {
                decoded.push(bytes[at]);
                at += 1;
            }
        }
    }
    String::from_utf8_lossy(&decoded).into_owned()
}

/// A machine-readable failure in the shape `/api/map` and `/api/diff`
/// already use, so the dashboard has one error shape to render.
fn json_error(stream: &mut TcpStream, status: &str, message: &str) -> std::io::Result<()> {
    let body = serde_json::json!({ "error": message });
    respond(
        stream,
        status,
        "application/json",
        body.to_string().as_bytes(),
    )
}

/// Writes one response and ends the connection. Every route funnels through
/// here (or through [`respond_head`], its body-withholding half), which is
/// the point: the hang-up below is not something a route can be written
/// without.
fn respond(
    stream: &mut TcpStream,
    status: &str,
    content_type: &str,
    body: &[u8],
) -> std::io::Result<()> {
    transmit(stream, status, content_type, None, body, true)
}

/// [`respond`] for the one status that owes a header beyond the shared
/// three: every 405 MUST carry `Allow` naming the target's served methods
/// (RFC 9110 §15.5.6), and threading it through [`transmit`] rather than a
/// second write path is what keeps the hang-up below something a refusal
/// cannot be written without.
fn respond_method_not_allowed(
    stream: &mut TcpStream,
    allow: &str,
    body: &[u8],
) -> std::io::Result<()> {
    transmit(
        stream,
        "405 Method Not Allowed",
        "text/plain",
        Some(allow),
        body,
        true,
    )
}

/// [`respond`] for a HEAD: the same status line and the same headers —
/// `Content-Length` carrying the length of the body a GET would have sent,
/// which RFC 9110 §9.3.2 asks for — and no body bytes. Sharing
/// [`transmit`] with `respond` is what makes "same status and headers" a
/// property of the code rather than a discipline.
fn respond_head(
    stream: &mut TcpStream,
    status: &str,
    content_type: &str,
    body: &[u8],
) -> std::io::Result<()> {
    transmit(stream, status, content_type, None, body, false)
}

/// The one wire format every responder shares. `send_body` false is HEAD's
/// half: everything up to the blank line is written identically, then the
/// body is withheld rather than recomputed, so the promised length can
/// never be a different body's. `allow` is the 405's half: `Some` exactly
/// there, carrying the served-methods list that refusal owes (RFC 9110
/// §15.5.6); every other response has no claim to make about methods.
fn transmit(
    stream: &mut TcpStream,
    status: &str,
    content_type: &str,
    allow: Option<&str>,
    body: &[u8],
    send_body: bool,
) -> std::io::Result<()> {
    write!(
        stream,
        "HTTP/1.1 {status}\r\nContent-Type: {content_type}\r\nContent-Length: {}\r\nConnection: close\r\n",
        body.len()
    )?;
    if let Some(allow) = allow {
        write!(stream, "Allow: {allow}\r\n")?;
    }
    write!(stream, "\r\n")?;
    if send_body {
        stream.write_all(body)?;
    }
    stream.flush()?;
    hang_up(stream);
    Ok(())
}

/// Ends a connection without cutting off the response just written.
///
/// A socket closed while unread bytes are still queued against it is closed
/// with an RST rather than a FIN, and an RST tells the peer's kernel to
/// abandon what it has buffered — including a response written a moment
/// earlier. So the client of a refusal reads a connection reset instead of
/// the reason it was refused. Every refusal this server writes is decided
/// from the request line and the headers, which is exactly the moment a body
/// is most likely to still be arriving.
///
/// The two halves do different jobs, and the order between them is the
/// decision rather than a detail. Shutting the write side down first sends
/// the FIN that ends the client's read, so the response is delivered before
/// anything at all is waited on; the client, having read it, closes, and the
/// drain then reaches EOF at once instead of sitting out a timeout. The
/// drain is what makes the eventual close a FIN rather than an RST. Doing it
/// the other way round — read the client out, then answer — would make the
/// server wait on a client that has not finished sending, and it would put
/// that wait in front of the response rather than behind it.
///
/// Bounded three ways, because an unauthenticated local caller picks every
/// number this loop is not given: [`MAX_DRAIN`] bytes, [`LINGER_TIMEOUT`] on
/// a client that goes quiet, and [`DRAIN_DEADLINE`] across the loop as a
/// whole. The last is the one that makes the other two add up to anything —
/// bytes and silence are both bounds a busy client never reaches. Nothing is
/// kept — the bytes pass through one stack buffer and are dropped — so a
/// route that was never going to read a body still never allocates one for
/// it.
fn hang_up(stream: &mut TcpStream) {
    if stream.shutdown(Shutdown::Write).is_err() {
        // Already gone; there is nobody left to be polite to.
        return;
    }
    let deadline = Instant::now() + DRAIN_DEADLINE;
    let mut scratch = [0u8; 4096];
    let mut drained = 0;
    while drained < MAX_DRAIN {
        let left = deadline.saturating_duration_since(Instant::now());
        // Out of budget, or the budget would not go onto the socket. The
        // second is why this is not `let _ =`: a failed `set_read_timeout`
        // leaves the stream on the ten-second `READ_TIMEOUT`, and the
        // deadline is only consulted between reads, so one read could sit
        // there for ten times the bound this function documents. Stopping
        // instead costs a client that is still sending the response it was
        // owed — exactly what the `MAX_DRAIN` break already costs, and the
        // price of a bound being a bound.
        if left.is_zero()
            || stream
                .set_read_timeout(Some(left.min(LINGER_TIMEOUT)))
                .is_err()
        {
            break;
        }
        match stream.read(&mut scratch) {
            // EOF, a timeout, or a peer that hung up first: done either way.
            Ok(0) | Err(_) => break,
            Ok(read) => drained += read,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn accepted_connections_carry_a_read_timeout() {
        // Ticket 15 carry-over (review finding on ticket 09): a client that
        // connects and then sends nothing must not park a handler thread
        // forever — every accepted stream gets a finite read timeout, so a
        // half-open request errors out and the thread exits. Asserting the
        // configured timeout (rather than waiting it out) keeps the test
        // instant; the timeout value itself is not behavior worth pinning
        // beyond "finite".
        let listener = TcpListener::bind((Ipv4Addr::LOCALHOST, 0)).unwrap();
        let addr = listener.local_addr().unwrap();
        let _client = TcpStream::connect(addr).unwrap();
        let (stream, _) = listener.accept().unwrap();

        let stream = prepare(stream).unwrap();
        assert_eq!(stream.read_timeout().unwrap(), Some(READ_TIMEOUT));
    }

    #[test]
    fn the_source_cut_excludes_a_split_character_rather_than_inventing_one() {
        // A two-byte scalar straddling the cap: its lead byte the last byte
        // inside, its continuation byte the first outside. Cutting between
        // them would put a replacement character at the end of an honest
        // file; the cut must exclude the scalar whole instead.
        let mut straddled = vec![b'a'; MAX_SOURCE_BYTES - 1];
        straddled.extend_from_slice("é".as_bytes());
        straddled.extend_from_slice(b"tail");
        let clipped = clip(&straddled);
        assert_eq!(
            clipped.len(),
            MAX_SOURCE_BYTES - 1,
            "the split character must be excluded whole"
        );
        assert!(
            std::str::from_utf8(clipped).is_ok(),
            "the cut must land on a character boundary"
        );

        // The control pair: pure ASCII cuts at exactly the cap, and an
        // under-cap file is untouched.
        let ascii = vec![b'a'; MAX_SOURCE_BYTES + 10];
        assert_eq!(clip(&ascii).len(), MAX_SOURCE_BYTES);
        assert_eq!(clip(b"fits"), b"fits");
    }
}
