//! `codeatlas serve`: the embedded dashboard over loopback (ticket 09), and
//! — only when asked for — questions about the map (ticket 34).
//!
//! The server is a hand-rolled HTTP/1.1 responder on `std::net::TcpListener`
//! rather than a server crate: four GET routes, one optional POST, and zero
//! TLS/streaming/routing machinery, so even the smallest server dependency
//! (tiny_http and its transitive tree) would be more code than this file.
//! Under ADR-0006 the serve path must survive a security audit by reading it
//! — a screenful of std with one hardcoded loopback bind is the strongest
//! form of that argument.
//!
//! # Two shapes, and the difference is a flag
//!
//! Without `--ask` this process reaches for four things and no others: one
//! listening socket on 127.0.0.1, asset bytes from process memory, the map
//! and overlay from local disk, and one sentence it composes about its own
//! configuration (the capability route below, which is not read from
//! anywhere — it is `routes.ask.is_some()`). Nothing off this host, ever,
//! which is what the netns egress test puts a real subject under.
//!
//! With `--ask` the binary also holds an enrichment provider, and
//! `POST /api/ask` reaches a model through it (ADR-0009). That is opt-in,
//! resolved before the socket is bound so a build or a machine that cannot
//! answer questions says so at startup rather than on the first question.
//!
//! Which of the two shapes is running is what `GET /api/capabilities` states,
//! for the dashboard (ticket 27): the same embedded bytes are served either
//! way, so the page has to be told at runtime rather than at build time. It
//! is not in the map, because whether one process was started with a flag is
//! not a property of a map — and the map's schema is a published contract
//! other producers emit against (ADR-0003).

use std::io::{BufRead, BufReader, Read, Write};
use std::net::{Ipv4Addr, TcpListener, TcpStream};
use std::path::{Path, PathBuf};
use std::thread;
use std::time::Duration;

use anyhow::{Context, Result, bail};

use crate::enrich::{self, EnrichmentProvider, ProviderChoice, SharedProvider, ask};
use crate::map::KnowledgeGraph;
use crate::scan::OUTPUT_DIR;

// Generated by build.rs: `ASSETS`, the dashboard production build keyed by
// URL path with precomputed MIME types.
include!(concat!(env!("OUT_DIR"), "/embedded_assets.rs"));

/// How `serve` was asked to run.
pub struct ServeOptions<'a> {
    pub port: u16,
    /// `Some` exactly when `--ask` was given: the backend to answer
    /// questions through. `None` leaves `POST /api/ask` non-existent.
    pub ask: Option<ProviderChoice<'a>>,
}

/// Serves the embedded dashboard, `<root>/.codeatlas/knowledge-graph.json`,
/// and — when present — the diff overlay next to it, on 127.0.0.1 until the
/// process is interrupted. Loopback is hardcoded — the listener cannot be
/// pointed at a routable interface (ADR-0006). Port 0 asks the OS for a free
/// port; the actually bound URL is printed to stdout.
///
/// With [`ServeOptions::ask`] set, `POST /api/ask` is served too.
pub fn serve(root: &Path, options: ServeOptions<'_>) -> Result<()> {
    // Before anything else, including the map check: whether this binary can
    // answer questions at all is a property of how it was compiled, and a
    // sealed build should say so rather than get as far as complaining about
    // the repository (ADR-0006, ADR-0009).
    let ask = options
        .ask
        .map(|choice| {
            enrich::resolve_provider(choice)
                .map(SharedProvider::from)
                .context("`serve --ask` needs an enrichment backend")
        })
        .transpose()?;

    let root = root
        .canonicalize()
        .with_context(|| format!("cannot serve {}", root.display()))?;
    let map_path = root.join(OUTPUT_DIR).join("knowledge-graph.json");
    let overlay_path = root.join(OUTPUT_DIR).join(crate::diff::OVERLAY_FILE);
    if !map_path.exists() {
        bail!(
            "no map at {} — run `codeatlas scan {}` first",
            map_path.display(),
            root.display()
        );
    }
    let routes = Routes {
        map_path,
        overlay_path,
        ask,
    };

    let port = options.port;
    let listener = TcpListener::bind((Ipv4Addr::LOCALHOST, port)).with_context(|| {
        format!("cannot bind 127.0.0.1:{port} — is the port in use? (--port picks another; 0 lets the OS choose)")
    })?;
    let addr = listener.local_addr()?;
    // The URL goes to stdout so scripts (and the e2e test) can capture it;
    // stdout is line-buffered, so the line is visible before we block.
    println!("CodeAtlas dashboard at http://{addr}/");
    eprintln!("serving {} — press Ctrl-C to stop", root.display());
    if routes.ask.is_some() {
        eprintln!("answering questions at POST http://{addr}{ASK_ROUTE}");
    }

    // Ctrl-C ends the process (default SIGINT handling); nothing to clean up
    // beyond what the OS reclaims. One thread per connection: browsers open
    // parallel connections for assets, and blocking them behind one another
    // stalls first paint.
    for stream in listener.incoming() {
        let Ok(stream) = stream else { continue };
        let routes = routes.clone();
        thread::spawn(move || {
            // Per-connection errors (client hung up mid-request) only affect
            // that client; the server must outlive them — including when the
            // question backend fails, which is an ordinary response here
            // rather than an end to serving (spec story 14's rule).
            let _ = handle(stream, &routes);
        });
    }
    Ok(())
}

/// The route a question is asked on. One constant because the server prints
/// it, routes on it, and the dashboard fetches it.
pub const ASK_ROUTE: &str = "/api/ask";

/// Where the dashboard reads what this server process can do. One field
/// today — whether [`ASK_ROUTE`] exists — because that is the one thing the
/// page cannot work out for itself: it is the same build either way, and the
/// alternative to being told is POSTing a question nobody asked to see
/// whether the route is there.
pub const CAPABILITIES_ROUTE: &str = "/api/capabilities";

/// What a connection may be answered from. Cloned per connection: two
/// paths and, when `--ask` was given, a shared handle on the provider.
#[derive(Clone)]
struct Routes {
    map_path: PathBuf,
    overlay_path: PathBuf,
    /// Present exactly when `serve --ask` was given. `None` is what makes
    /// `POST /api/ask` a 405 like any other non-GET: the route does not
    /// exist rather than existing and refusing.
    ask: Option<SharedProvider>,
}

/// How long a handler thread waits on a read before giving up on the
/// connection. Generous for a loopback client, but finite: a client that
/// connects and never finishes its request must not park a thread forever.
const READ_TIMEOUT: Duration = Duration::from_secs(10);

/// Per-connection socket setup: every accepted stream gets [`READ_TIMEOUT`]
/// so a half-open request errors out instead of blocking its thread
/// indefinitely.
fn prepare(stream: TcpStream) -> std::io::Result<TcpStream> {
    stream.set_read_timeout(Some(READ_TIMEOUT))?;
    Ok(stream)
}

/// The most bytes a request body may carry. A question is a sentence in a
/// small JSON object; anything larger is a mistake or an attempt to make a
/// hand-rolled server allocate on demand.
const MAX_BODY: usize = 64 * 1024;

/// How much of an over-long body to read before answering 413. Replying
/// without reading the client out can reset the connection in its face, so
/// an oversized request is swallowed up to here and then refused; past this,
/// being tidy is not worth the bytes.
const MAX_DRAIN: usize = 16 * MAX_BODY;

/// The two request headers this server reads. It read none before ADR-0009,
/// and reads exactly these now — one to frame a body, one to refuse a
/// request no honest client would send (see [`answer_question`]).
#[derive(Default)]
struct Headers {
    content_length: usize,
    content_type: String,
}

/// Consumes the header block, keeping only [`Headers`]. An unparseable
/// content length reads as no body, and the route that wanted one rejects
/// the empty request on its own terms.
fn read_headers(reader: &mut BufReader<TcpStream>) -> std::io::Result<Headers> {
    let mut headers = Headers::default();
    loop {
        let mut line = String::new();
        if reader.read_line(&mut line)? == 0 || line == "\r\n" || line == "\n" {
            return Ok(headers);
        }
        let Some((name, value)) = line.split_once(':') else {
            continue;
        };
        let value = value.trim();
        if name.eq_ignore_ascii_case("content-length") {
            headers.content_length = value.parse().unwrap_or(0);
        } else if name.eq_ignore_ascii_case("content-type") {
            headers.content_type = value.to_ascii_lowercase();
        }
    }
}

/// Answers one request and closes the connection (`Connection: close` — the
/// dashboard is a handful of requests, keep-alive buys nothing but state).
fn handle(stream: TcpStream, routes: &Routes) -> std::io::Result<()> {
    let mut reader = BufReader::new(prepare(stream)?);
    let mut request_line = String::new();
    reader.read_line(&mut request_line)?;
    let headers = read_headers(&mut reader)?;

    let mut parts = request_line.split_whitespace();
    let (method, target) = match (parts.next(), parts.next()) {
        (Some(m), Some(t)) => (m.to_string(), t.to_string()),
        _ => {
            let mut stream = reader.into_inner();
            return respond(&mut stream, "400 Bad Request", "text/plain", b"bad request");
        }
    };
    let path = target.split(['?', '#']).next().unwrap_or(&target);

    // The one non-GET route, and only when `--ask` put a backend behind it.
    // Reading a body is confined to this branch on purpose: without `--ask`
    // the server ignores one exactly as it did before ADR-0009, so its
    // behaviour on every other route is unchanged rather than merely
    // similar.
    if method == "POST"
        && path == ASK_ROUTE
        && let Some(provider) = &routes.ask
    {
        return answer_question(reader, routes, provider.as_ref(), &headers);
    }

    let mut stream = reader.into_inner();
    if method != "GET" {
        // Build-aware, because with `--ask` the flat claim is false — and a
        // reader who mistyped the question route deserves to be told the
        // right one rather than that POST is unsupported.
        let served: &[u8] = match routes.ask {
            Some(_) => b"only GET, and POST /api/ask, are served",
            None => b"only GET is served",
        };
        return respond(&mut stream, "405 Method Not Allowed", "text/plain", served);
    }

    if path == "/api/map" {
        // Read from disk per request so a re-scan shows up on refresh.
        return match std::fs::read(&routes.map_path) {
            Ok(map) => respond(&mut stream, "200 OK", "application/json", &map),
            Err(_) => respond(
                &mut stream,
                "404 Not Found",
                "application/json",
                format!(
                    "{{\"error\":\"no map at {} — run `codeatlas scan` first\"}}",
                    routes.map_path.display()
                )
                .as_bytes(),
            ),
        };
    }

    if path == CAPABILITIES_ROUTE {
        // Always 200, always answered, in every build: an absent route and a
        // route saying "no" would be two ways to express one fact, and the
        // client would have to treat them the same anyway.
        return respond(
            &mut stream,
            "200 OK",
            "application/json",
            format!("{{\"ask\":{}}}", routes.ask.is_some()).as_bytes(),
        );
    }

    if path == "/api/diff" {
        // The overlay is optional: absent means `codeatlas diff` has not
        // run, and the dashboard hides its toggle on the 404.
        return match std::fs::read(&routes.overlay_path) {
            Ok(overlay) => respond(&mut stream, "200 OK", "application/json", &overlay),
            Err(_) => respond(
                &mut stream,
                "404 Not Found",
                "application/json",
                b"{\"error\":\"no diff overlay - run `codeatlas diff` first\"}",
            ),
        };
    }

    let asset_path = match path.trim_start_matches('/') {
        "" => "index.html",
        rest => rest,
    };
    match ASSETS.iter().find(|a| a.path == asset_path) {
        Some(asset) => respond(&mut stream, "200 OK", asset.content_type, asset.bytes),
        None => respond(&mut stream, "404 Not Found", "text/plain", b"not found"),
    }
}

/// The request body `POST /api/ask` accepts. One field, so the dashboard's
/// half of the story (ticket 27) is a `fetch` with a one-line body.
#[derive(serde::Deserialize)]
struct AskBody {
    question: String,
}

/// The content type a question must be sent as.
///
/// Not politeness — it is what stops an arbitrary web page in the reader's
/// browser from spending their model budget while `serve --ask` is running.
/// A cross-origin `fetch` or form post can only set the three "simple"
/// content types without a CORS preflight; demanding this one forces a
/// preflight, and this server answers no `OPTIONS`, so the browser never
/// sends the request. Same-origin callers — the dashboard, ticket 27 — are
/// unaffected, and `curl` simply sets the header.
const ASK_CONTENT_TYPE: &str = "application/json";

/// Answers one question, or explains why it cannot. Every outcome is a
/// response: a failing backend must not take the server down with it, which
/// is spec story 14's rule applied to a route rather than to a scan.
///
/// The statuses distinguish who can fix the problem. A question that is
/// blank, over-long, or not JSON is a 400 the reader can act on; a backend
/// that would not answer is a 502, because nothing about the request was
/// wrong.
fn answer_question(
    mut reader: BufReader<TcpStream>,
    routes: &Routes,
    provider: &dyn EnrichmentProvider,
    headers: &Headers,
) -> std::io::Result<()> {
    // Read the client out before replying, whatever the verdict: answering
    // a request still being written can reset the connection in its face.
    let mut body = Vec::new();
    reader
        .by_ref()
        .take(headers.content_length.min(MAX_DRAIN) as u64)
        .read_to_end(&mut body)?;
    let stream = &mut reader.into_inner();

    if headers.content_length > MAX_BODY {
        return json_error(
            stream,
            "413 Payload Too Large",
            &format!("the request body may be at most {MAX_BODY} bytes"),
        );
    }
    if !headers.content_type.starts_with(ASK_CONTENT_TYPE) {
        return json_error(
            stream,
            "415 Unsupported Media Type",
            &format!("questions must be sent as {ASK_CONTENT_TYPE}"),
        );
    }

    let asked = match serde_json::from_slice::<AskBody>(&body) {
        Ok(asked) => asked,
        Err(err) => {
            return json_error(
                stream,
                "400 Bad Request",
                &format!("the body must be JSON of the form {{\"question\": \"…\"}}: {err}"),
            );
        }
    };

    // Re-read per request, exactly as `/api/map` does, so a re-scan while
    // the server runs is answered against the new map.
    let graph = match read_graph(&routes.map_path) {
        Ok(graph) => graph,
        Err(err) => {
            return json_error(
                stream,
                "500 Internal Server Error",
                &format!(
                    "cannot read the map at {}: {err:#}",
                    routes.map_path.display()
                ),
            );
        }
    };

    let question = match ask::build(&graph, &asked.question) {
        Ok(question) => question,
        Err(err) => return json_error(stream, "400 Bad Request", &format!("{err:#}")),
    };
    match ask::answer(provider, &question) {
        Ok(answer) => {
            let payload = serde_json::json!({
                "answer": answer.text,
                "citations": answer.citations,
            });
            respond(
                stream,
                "200 OK",
                "application/json",
                payload.to_string().as_bytes(),
            )
        }
        Err(err) => json_error(stream, "502 Bad Gateway", &format!("{err:#}")),
    }
}

fn read_graph(map_path: &Path) -> anyhow::Result<KnowledgeGraph> {
    Ok(serde_json::from_slice(&std::fs::read(map_path)?)?)
}

/// A machine-readable failure in the shape `/api/map` and `/api/diff`
/// already use, so the dashboard has one error shape to render.
fn json_error(stream: &mut TcpStream, status: &str, message: &str) -> std::io::Result<()> {
    let body = serde_json::json!({ "error": message });
    respond(
        stream,
        status,
        "application/json",
        body.to_string().as_bytes(),
    )
}

fn respond(
    stream: &mut TcpStream,
    status: &str,
    content_type: &str,
    body: &[u8],
) -> std::io::Result<()> {
    write!(
        stream,
        "HTTP/1.1 {status}\r\nContent-Type: {content_type}\r\nContent-Length: {}\r\nConnection: close\r\n\r\n",
        body.len()
    )?;
    stream.write_all(body)?;
    stream.flush()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn accepted_connections_carry_a_read_timeout() {
        // Ticket 15 carry-over (review finding on ticket 09): a client that
        // connects and then sends nothing must not park a handler thread
        // forever — every accepted stream gets a finite read timeout, so a
        // half-open request errors out and the thread exits. Asserting the
        // configured timeout (rather than waiting it out) keeps the test
        // instant; the timeout value itself is not behavior worth pinning
        // beyond "finite".
        let listener = TcpListener::bind((Ipv4Addr::LOCALHOST, 0)).unwrap();
        let addr = listener.local_addr().unwrap();
        let _client = TcpStream::connect(addr).unwrap();
        let (stream, _) = listener.accept().unwrap();

        let stream = prepare(stream).unwrap();
        assert_eq!(stream.read_timeout().unwrap(), Some(READ_TIMEOUT));
    }
}
